/**
 * Annotation namespace for effect-admin.
 *
 * This package is deliberately dependency-free (decision D3): a host app
 * annotates its own schemas in-place, and the only coupling it takes on
 * is this one symbol plus its types. `Symbol.for` keeps the symbol stable
 * across duplicated installs.
 *
 * A single symbol carrying an object — not one symbol per flag — so future
 * extensions extend the object without touching the public API.
 */
export const AdminField = Symbol.for("effect-admin/AdminField")

export interface AdminFieldAnnotation {
  /** Field is generated by the system (pk, timestamps): excluded from `create`. */
  readonly auto?: boolean
  /**
   * ForeignKey target: the resource name this field references (roadmap F4).
   * Read but not acted upon before F4 — safe to annotate from day one.
   */
  readonly ref?: string
  /** Which field of the referenced resource to show as label (roadmap F4). */
  readonly displayField?: string
  /** Never render this field in generated admin screens. */
  readonly hidden?: boolean
  /** Show the value, but never include it in generated create/update forms. */
  readonly readOnly?: boolean
  /** Mask the value in detail and list screens. */
  readonly sensitive?: boolean
}
